In [1]:
import numpy as np

A = np.array([[2,3,4],[6,1,6],[0,-6,-5]])
print(A.T)

[[ 2  6  0]
 [ 3  1 -6]
 [ 4  6 -5]]


In [1]:
import numpy as np

A = np.array([[1,9],[0,1]])
A6 = np.linalg.matrix_power(A,6)
print(A6)

[[ 1 54]
 [ 0  1]]


In [3]:
import numpy as np

A = np.array([[3,3],[8,2]])
# find the upper triangular matrix U for the LU factorization of A.
U = np.linalg.qr(A)[1]
print(U)

[[-8.54400375 -2.92602868]
 [ 0.         -2.10674065]]


In [4]:
import numpy as np

A = np.array([[3,7],[7,4]])
# find det
det = np.linalg.det(A)
print(det)

-36.99999999999999


In [5]:
import numpy as np

A = np.array([[5,1],[5,7]])
# find the lower triangular matrix L for the LU factorization of A.
L = np.linalg.qr(A.T)[1].T
print(L)

[[-5.09901951  0.        ]
 [-6.27571632  5.88348405]]


In [6]:
import numpy as np

P = np.array([[0,1,0],[0,0,1],[1,0,0]])
A = np.array([[9,9,5],[-4,0,3],[-5,4,5]])
# find the matrix PA
PA = P.dot(A)
print(PA)

[[-4  0  3]
 [-5  4  5]
 [ 9  9  5]]


In [7]:
import numpy as np

u = np.array([[6,3,4]])
v = np.array([[8,5,10]])
# Find the angle θ (in degree) between these two vectors.
theta = np.arccos(u.dot(v.T)/(np.linalg.norm(u)*np.linalg.norm(v)))*180/np.pi
print(theta)

[[16.40867841]]
