In [50]:
import numpy as np


def mat_randint(s):
    return np.random.randint(low=1, high=9, size=(s, s))


def mat_elim(A):
	return np.linalg.inv(A) @ A


# A = mat_randint(3)
A = np.array([[1, 1, 8],
              [5, 1, 3],
              [7, 6, 6]])
print("\nA = \n", A)
E = mat_elim(A)
print("\nE = \n", E)
print("\nEA = \n", np.around(E @ A, 3))



A = 
 [[1 1 8]
 [5 1 3]
 [7 6 6]]

E = 
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00  0.00000000e+00]
 [ 2.77555756e-17  0.00000000e+00  1.00000000e+00]]

EA = 
 [[1. 1. 8.]
 [5. 1. 3.]
 [7. 6. 6.]]
