In [1]:
import numpy as np


def mat_randint(s):
    return np.random.randint(low=1, high=9, size=(s, s))


def mat_elim(A):
    E1 = np.eye(A.shape[0])
    E1[1, 0] = -A[1, 0] / A[0, 0]
    A1 = E1 @ A

    E2 = np.eye(A.shape[0])
    E2[2, 0] = -A1[2, 0] / A1[0, 0]
    A2 = E2 @ A1

    E3 = np.eye(A.shape[0])
    E3[2, 1] = -A2[2, 1] / A2[1, 1]
    A3 = E3 @ A2

    return E3 @ (E2 @ E1)


A = mat_randint(3)
print("\nA = \n", A)
E = mat_elim(A)
print("\nE = \n", E)
print("\nEA = \n", np.around(E @ A, 3))



A = 
 [[2 4 8]
 [2 2 8]
 [6 7 4]]

E = 
 [[ 1.   0.   0. ]
 [-1.   1.   0. ]
 [-0.5 -2.5  1. ]]

EA = 
 [[  2.   4.   8.]
 [  0.  -2.   0.]
 [  0.   0. -20.]]
